[dask]
workers = 1
files = [
    "orderp.py",
    "gromacs.py",
]
wmdrun = [
    "gmx mdrun",
    "gmx mdrun",
]

[simulation]
pyretis_inp = "retis.rst"
internal = false
interfaces = [-0.26, -0.24, -0.22]
shooting_moves = ['sh', 'sh', 'sh']
steps = 50
seed = 0
save_loc = "./"
load_dir = "trajs"

[simulation.tis_set]
maxlength = 20000
aimless = true
allowmaxlength = false
zero_momentum = false
rescale_energy = false
n_jumps = 3
high_accept = true

[engine]
engine = "random"
class = "GromacsEngineR"
input_path = "gromacs_input"
module = "gromacs.py"
gmx = "gmx"
mdrun = "mdrun"
timestep = 0.002
subcycles = 1
gmx_format = "g96"
maxwarn = 15

[orderparameter]
orderparameter = "RingDiffusion"
class = "RingDiffusion"
module = "orderp.py"
index = [
    0,
    1,
]
periodic = false

[output]
backup = "backup"
store_paths = true
screen = 1
pattern = true
data_dir = "./"
