[dask]
workers = 1
files = [
    "orderp.py",
    "gromacs.py",
]

[simulation]
pyretis_inp = "retis.rst"
internal = false
interfaces = [-0.26, -0.24, -0.22]
shooting_moves = ['sh', 'sh', 'sh']
steps = 10
seed = 0
save_loc = "./"
load_dir = "trajs"

[engine]
engine = "gromacs"
class = "GromacsEngine2R"
input_path = "gromacs_input"
module = "gromacs.py"
gmx = "gmx"
mdrun = "mdrun"
timestep = 0.002
subcycles = 1
gmx_format = "gro"
maxwarn = 15

[order_parameter]
class = "Distance"
index = [
    0,
    1,
]
periodic = false

[output]
backup = "backup"
store_paths = true
screen = 1
pattern = true
data_dir = "./"
