[project]
name = "infretis"
version = "0.0.1"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
infretisrun = "infretis.infretisrun:entry_point"
infretisanalyse= "infretis.infretisrun:entry_point"


