[dask]
workers = 1

[simulation]
pyretis_inp = "retis.rst"
internal = true
states_ab = [
    0.27,
    0.45,
]
steps = 50
seed = 0
save_loc = "./"

[output]
backup = "backup"
store_paths = true
screen = 1
pattern = true
data_dir = "./"
