name: Spelling Check

on:
  pull_request:
    paths:
      - '**.py'
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.md'
  workflow_dispatch:

jobs:
  check-spelling:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper change detection
          fetch-depth: 0

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: "Install codespell"
        run: pip install codespell

      - name: "Get changed files"
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PRs, compare with the base branch
            BASE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} HEAD)
            CHANGED_FILES=$(git diff --name-only $BASE_SHA HEAD -- '*.py' '*.md' | xargs)
          else
            # For pushes to main, use the previous commit
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- '*.py' '*.md' | xargs)
          fi
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: "Run codespell on changed files"
        env:
          ALL_CHANGED_FILES: ${{ env.CHANGED_FILES }}
        run: |
          IFS=' ' read -r -a files_array <<< "$ALL_CHANGED_FILES"
          for file in "${files_array[@]}"; do
            echo "$file was changed"
            if [[ "$file" == *.py || "$file" == *.md ]]; then
              echo "Checking: $file"
              spell_output=$(codespell "$file" 2>&1) || true
              if [ -n "$spell_output" ]; then
                  echo "::warning file=$file::$spell_output"
              fi
            else
                echo "Skipping: $file (not .py or .md)"
            fi
          done
